---
title: सरल Python list comprehensions
hero_image: images/banner.png
description: Python के साथ एक पंक्ति में सूचियाँ बनाएं
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
site_areas:
steps:
  - 
    title: सूचियाँ बनाना

